# Form implementation generated from reading ui file 'Dosemap_display.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(868, 759)
        self.groupBox_6 = QtWidgets.QGroupBox(parent=Form)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 20, 401, 350))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setStyleSheet("border-radius:5px;\n"
"border: 1px solid #cfcfcf;\n"
"padding-top:7px;\n"
"")
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem)
        self.dvh_combo = QtWidgets.QComboBox(parent=self.groupBox_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.dvh_combo.setFont(font)
        self.dvh_combo.setStyleSheet("border-radius:5px;\n"
"font: 11pt \"Arial\";\n"
"background:#fcfcfc;\n"
"color:#000000;\n"
"border:1px solid #d0d0d0;\n"
"padding:1px 15px;\n"
"margin-right:0px;")
        self.dvh_combo.setObjectName("dvh_combo")
        self.horizontalLayout_35.addWidget(self.dvh_combo)
        self.verticalLayout_3.addLayout(self.horizontalLayout_35)
        self.dvhView = Dvh_Label(parent=self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dvhView.sizePolicy().hasHeightForWidth())
        self.dvhView.setSizePolicy(sizePolicy)
        self.dvhView.setMinimumSize(QtCore.QSize(0, 150))
        self.dvhView.setMaximumSize(QtCore.QSize(389, 285))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.dvhView.setFont(font)
        self.dvhView.setStyleSheet("margin-left: 0;")
        self.dvhView.setText("")
        self.dvhView.setObjectName("dvhView")
        self.verticalLayout_3.addWidget(self.dvhView)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        spacerItem1 = QtWidgets.QSpacerItem(362, 17, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem1)
        self.histogramSaveBtn = QtWidgets.QPushButton(parent=self.groupBox_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.histogramSaveBtn.setFont(font)
        self.histogramSaveBtn.setStyleSheet("border-radius:5px;\n"
"background:#fcfcfc;\n"
"color:#000000;\n"
"border:1px solid #d0d0d0;\n"
"padding:5px 15px;\n"
"font-size:11pt")
        self.histogramSaveBtn.setObjectName("histogramSaveBtn")
        self.horizontalLayout_23.addWidget(self.histogramSaveBtn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_23)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 50)
        self.verticalLayout_3.setStretch(2, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(parent=Form)
        self.groupBox_7.setGeometry(QtCore.QRect(20, 380, 831, 351))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setStyleSheet("border-radius:5px;\n"
"border: 1px solid #cfcfcf;\n"
"padding-top:15px;\n"
"\n"
"\n"
"")
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.dmView1 = Dvh_Map(parent=self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dmView1.sizePolicy().hasHeightForWidth())
        self.dmView1.setSizePolicy(sizePolicy)
        self.dmView1.setMinimumSize(QtCore.QSize(0, 150))
        self.dmView1.setMaximumSize(QtCore.QSize(393, 273))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.dmView1.setFont(font)
        self.dmView1.setStyleSheet("margin-right: 0;")
        self.dmView1.setText("")
        self.dmView1.setObjectName("dmView1")
        self.verticalLayout_6.addWidget(self.dmView1)
        self.verticalLayout_6.setStretch(0, 1)
        self.verticalLayout_6.setStretch(1, 50)
        self.horizontalLayout_24.addLayout(self.verticalLayout_6)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem3)
        self.dm_combo2 = QtWidgets.QComboBox(parent=self.groupBox_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.dm_combo2.setFont(font)
        self.dm_combo2.setStyleSheet("border-radius:5px;\n"
"font: 11pt \"Arial\";\n"
"background:#fcfcfc;\n"
"color:#000000;\n"
"border:1px solid #d0d0d0;\n"
"padding:1px 15px;\n"
"margin-right:0px;")
        self.dm_combo2.setObjectName("dm_combo2")
        self.dm_combo2.addItem("")
        self.dm_combo2.addItem("")
        self.dm_combo2.addItem("")
        self.horizontalLayout_25.addWidget(self.dm_combo2)
        self.verticalLayout_15.addLayout(self.horizontalLayout_25)
        self.dmView2 = Dvh_Contour(parent=self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dmView2.sizePolicy().hasHeightForWidth())
        self.dmView2.setSizePolicy(sizePolicy)
        self.dmView2.setMinimumSize(QtCore.QSize(0, 150))
        self.dmView2.setMaximumSize(QtCore.QSize(392, 273))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.dmView2.setFont(font)
        self.dmView2.setStyleSheet("margin-right:0;")
        self.dmView2.setText("")
        self.dmView2.setObjectName("dmView2")
        self.verticalLayout_15.addWidget(self.dmView2)
        self.verticalLayout_15.setStretch(0, 1)
        self.verticalLayout_15.setStretch(1, 50)
        self.horizontalLayout_24.addLayout(self.verticalLayout_15)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_6.setTitle(_translate("Form", "Dose volume histogram"))
        self.histogramSaveBtn.setText(_translate("Form", "Save"))
        self.groupBox_7.setTitle(_translate("Form", "Dose map / Iso-dose contour"))
        self.dm_combo2.setItemText(0, _translate("Form", "Axial"))
        self.dm_combo2.setItemText(1, _translate("Form", "Sagittal"))
        self.dm_combo2.setItemText(2, _translate("Form", "Coronal"))
from dvh_contour import Dvh_Contour
from dvh_label import Dvh_Label
from dvh_map import Dvh_Map
